"""Curated trail facts awaiting content-owner sign-off.

Season values follow the newer supplied September 2026 data document. They are
not live access reports. Coordinates are representative points, not route-wide
forecast assurance. Sources support editorial review, not a safety guarantee.
"""
from .content import trail_content

TRAILS = {'dalsnuten': {'name': 'Dalsnuten (Norway)',
               'region': 'Norway',
               'km': 3,
               'days': 1,
               'grade': 1,
               'diff': 1,
               'risk': 'a short steep push to the summit on an otherwise gentle trail',
               'exposure': False,
               'season': None,
               'season_note': 'Low hill near Stavanger, walkable year round, snow possible in '
                              'winter.',
               'latitude': 58.887,
               'longitude': 5.854,
               'elevation_m': 323,
               'sources': ['https://www.visitnorway.com/listings/hike-to-dalsnuten/30580/'],
               'typical_conditions': 'Weather and snow can still change footing in winter.'},
 'gaustatoppen': {'name': 'Gaustatoppen (Norway)',
                  'region': 'Norway',
                  'km': 9,
                  'days': 1,
                  'grade': 2,
                  'diff': 2,
                  'risk': 'a rocky final stretch after a steady climb',
                  'exposure': False,
                  'season': {'start': '06-20', 'end': '10-10'},
                  'season_note': 'High summit, snow-free roughly late June to early October.',
                  'latitude': 59.854,
                  'longitude': 8.655,
                  'elevation_m': 1883,
                  'sources': ['https://www.visitnorway.com/things-to-do/outdoor-activities/hiking/gaustatoppen/'],
                  'typical_conditions': 'The high plateau can be cold, windy, and snow-covered '
                                        'outside the typical window.'},
 'laugavegur': {'name': 'Laugavegur (Iceland)',
                'region': 'Iceland',
                'km': 55,
                'days': 4,
                'grade': 2,
                'diff': 3,
                'risk': 'long hiking days four days in a row',
                'exposure': False,
                'season': {'start': '06-25', 'end': '09-10'},
                'season_note': 'Serviced huts open late June to mid-September, cold river '
                               'crossings.',
                'latitude': 63.984,
                'longitude': -19.061,
                'elevation_m': 1050,
                'sources': ['https://www.fi.is/en/mountain-huts/faq'],
                'typical_conditions': 'River crossings, wind, and hut access need current local '
                                      'checks.'},
 'preikestolen': {'name': 'Preikestolen (Norway)',
                  'region': 'Norway',
                  'km': 8,
                  'days': 1,
                  'grade': 3,
                  'diff': 3,
                  'risk': 'two steep sections and exposed drops near the top',
                  'exposure': True,
                  'season': {'start': '05-01', 'end': '10-15'},
                  'season_note': 'Snow-free May to October, the cliff edge is unguarded.',
                  'latitude': 58.986,
                  'longitude': 6.19,
                  'elevation_m': 604,
                  'sources': ['https://www.routesnorth.com/outdoors/hiking-to-pulpit-rock/'],
                  'typical_conditions': 'The cliff edge is unguarded and weather can make rock '
                                        'slippery.'},
 'besseggen': {'name': 'Besseggen (Norway)',
               'region': 'Norway',
               'km': 14,
               'days': 1,
               'grade': 3,
               'diff': 3,
               'risk': 'a sharp, exposed ridge',
               'exposure': True,
               'season': {'start': '07-01', 'end': '09-30'},
               'season_note': 'Classic route needs the Gjende ferry, which runs about 1 July to '
                              'late September.',
               'latitude': 61.496,
               'longitude': 8.828,
               'elevation_m': 1743,
               'sources': ['https://besseggen.net/informasjon/gjendeferry/?lang=en'],
               'typical_conditions': 'Ferry timing, wind, and exposed terrain require a current '
                                     'check.'},
 'fimmvorduhals': {'name': 'Fimmvorduhals (Iceland)',
                   'region': 'Iceland',
                   'km': 25,
                   'days': 1,
                   'grade': 3,
                   'diff': 3,
                   'risk': 'a steep, long descent that stresses the knees',
                   'exposure': True,
                   'season': {'start': '06-25', 'end': '09-10'},
                   'season_note': 'Snow lingers into June, plus a short airy chained ridge on the '
                                  'Thorsmork descent.',
                   'latitude': 63.725,
                   'longitude': -19.37,
                   'elevation_m': 1110,
                   'sources': ['https://guidetoiceland.is/travel-iceland/drive/fimmvorduhals'],
                   'typical_conditions': 'Snow, wind, and the airy Kattarhryggur ridge need '
                                         'route-specific judgment.'},
 'kjeragbolten': {'name': 'Kjeragbolten (Norway)',
                  'region': 'Norway',
                  'km': 12,
                  'days': 1,
                  'grade': 3,
                  'diff': 3,
                  'risk': 'chain-assisted scrambles and big drops',
                  'exposure': True,
                  'season': {'start': '06-01', 'end': '09-30'},
                  'season_note': 'Trail and access road open once snow clears, chain scrambles and '
                                 'big drops.',
                  'latitude': 59.048,
                  'longitude': 6.593,
                  'elevation_m': 1084,
                  'sources': ['https://kjerag.info/hiking-to-kjerag/'],
                  'typical_conditions': 'Access roads, snow, and exposed rock can change the '
                                        'practical route.'},
 'trolltunga': {'name': 'Trolltunga (Norway)',
                'region': 'Norway',
                'km': 28,
                'days': 1,
                'grade': 4,
                'diff': 4,
                'risk': 'a long day with big elevation gain',
                'exposure': True,
                'season': {'start': '06-15', 'end': '09-15'},
                'season_note': 'Recommended unguided mid-June to mid-September, big drops at the '
                               'ledge.',
                'latitude': 60.124,
                'longitude': 6.74,
                'elevation_m': 1180,
                'sources': ['https://www.trolltunga.com/en/plan-your-hike/seasons'],
                'typical_conditions': 'This is a long day in changeable mountain weather with '
                                      'unguarded drops.'},
 'romsdalseggen': {'name': 'Romsdalseggen (Norway)',
                   'region': 'Norway',
                   'km': 11,
                   'days': 1,
                   'grade': 4,
                   'diff': 4,
                   'risk': 'a narrow, exposed ridge with chain scrambles',
                   'exposure': True,
                   'season': {'start': '06-12', 'end': '10-10'},
                   'season_note': 'Point-to-point ridge on the seasonal shuttle bus, about 12 June '
                                  'to mid-October.',
                   'latitude': 62.551,
                   'longitude': 7.774,
                   'elevation_m': 1200,
                   'sources': ['https://www.nor-way.no/en/routes/romsdalseggenbussen/'],
                   'typical_conditions': 'Exposure, wind, and transport timing should be checked '
                                         'before committing.'}}

for _trail_id, _record in TRAILS.items():
    _record["content"] = trail_content(_trail_id, _record.pop("typical_conditions"))
